name: Get workflow runs details from current repository

permissions: read-all

on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./get-wf.js');
            console.log(script({github, context}));