name: Get workflow runs details from current repository

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      primero_bis:
        description: 'Primer número'
        required: true
        type: number


jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const workflowRuns = await github.paginate('GET /repos/{owner}/{repo}/actions/runs', {
              owner,
              repo,
              per_page: 100
            });

            console.log(workflowRuns);