name: Simple GitHub API call

permissions: read-all

on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const emojis = await github.rest.emojis.get();
            console.log(emojis.data);
